### ISSUE TITLE
Do not simulate submissions and reporting service ping on identity check failure

### ISSUE THREAD

**Issue by anomit** [PowerLoom/snapshotter-lite-v2#37]
## Describe the bug 
The node ends up sending simulation submissions as well as a ping to the reporting service even if its identity check fails.

## To Reproduce
**Affected versions**:

1. Use a bad snapshotter address or private key in `.env` file
2. Run the node with `./build.sh` or `./build-dev.sh`

**Expected behavior**
The node should quit right after failed identity check and not proceed with simulation submissions as well as a ping to the reporting service.

**Proposed Solution**
As described above.

**Caveats**
NA

**Additional context**
NA

**Comment by xadahiya** [comment]
Fix pushed here https://github.com/PowerLoom/snapshotter-lite-v2/tree/fix/snapshotter_id_check

**Comment by anomit** [comment]
Following up internally on the results of testing this on our staging systems.

**Comment by xadahiya** [comment]
PR here https://github.com/PowerLoom/snapshotter-lite-v2/pull/85
