### ISSUE TITLE
RPC Helper - semaphore wrapper returning None on exception

### ISSUE THREAD

**Issue by anomit** [PowerLoom/snapshotter-lite-v2#47]
## Describe the bug 
This bug was found in the V1 nodeRPC utils, which are being reused in lite V2 node as well.

Complete details [here](https://github.com/PowerLoom/pooler/issues/97).

## To Reproduce
**Affected versions**: all releases so far

1. RPC endpoint returns an error either in status code or response body

**Expected behavior**
Read issue description linked above.

**Proposed Solution**
Read issue description linked above.

**Caveats**
NA

**Additional context**
NA

**Comment by Seth-Schmidt** [comment]
This issue is not present in the current V2 lite node, and the fix has been applied to all V1 use cases.

**Comment by anomit** [comment]
To be reviewed in Protocol V2 full node implementation.
