### ISSUE TITLE
Maintain state and return overall node health status for docker compose health check

### ISSUE THREAD

**Issue by anomit** [PowerLoom/snapshotter-lite-v2#63]
**Is your feature request related to a problem?**
The node should maintain an overall health state when it comes to processing status, network reachability etc: key parameters that can determine whether a node is failing or not.

**Describe the solution you'd like**
To begin with, a few state information can be considered against which issue notifications to the Powerloom reporting services, including Telegram bot as well as 3rd party integrations are already sent out.

* Epoch processing failures against the [epoch processing state transitions](https://docs.powerloom.io/docs/Protocol/Specifications/Epoch#state-transitions)
* [Simulation](https://docs.powerloom.io/docs/build-with-powerloom/snapshotter-node/lite-node-v2/monitoring#simulation-run-logs) failures

**Describe alternatives you've considered**
NA. No state is considered at the moment against the HTTP endpoint specified against the `healthcheck` entry in docker compose.

**Additional context**
NA

**Comment by anomit** [comment]
This is similar to the issue pointed out in the V1 lite node: https://github.com/PowerLoom/snapshotter-lite/issues/24

**Comment by xadahiya** [comment]
Moving to current iteration CC @anomit
