### ISSUE TITLE
Support local collector env flag DATA_MARKET_IN_REQUEST

### ISSUE THREAD

**Issue by anomit** [PowerLoom/snapshotter-lite-v2#82]
**Is your feature request related to a problem?**
Local collector should be passed the above flag with value set to `true` in docker compose for multi data market feature to work correctly.

**Describe the solution you'd like**
As described above.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by Seth-Schmidt** [comment]
This has been included as a part of the update for multiple data markets here: 4ad8e412407f29b1a5f5aa761e5c0eafd52b24df
